name: Foo / Bar / Test 4 with custom name
on:
  issue_comment:
  workflow_dispatch:
    inputs:
      foo:
        description: Foo description
        type: boolean
        required: true
      bar:
        description: Bar description
        type: boolean
        required: false
env:
  TEST: 123
jobs:
  Do-Something:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set-var
        run: |
          MY_VAR=${{ github.event.inputs.foo }}
      - name: echo my var
        run: |
          echo $MY_VAR
      - name: echo bar
        run: |
          echo '${{ github.event.inputs.bar }}' 
