name: Foo / Bar / Test 4 with custom name
on:
  issue_comment:
  workflow_dispatch:
    inputs:
      foo:
        description: Foo description
        type: boolean
        required: true
      bar:
        description: Bar description
        type: boolean
        required: false
env:
  TEST: 123
jobs:
  Do-Something:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test-foo-bar
        shell: bash
        run: |
          MY_VAR=${{ github.inputs.foo }} 
          echo $MY_VAR
          echo '${{ github.inputs.bar }}' 
