on:
  issue_comment:
    types: [created]
env:
  TEST: 123
jobs:
  Do-Something:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: echo
        shell: bash
        run: echo $TEST
